### PR TITLE
Add latest process diag #254

### LINKED ISSUE #254: Add latest process diagram into sphinx docs
Once the latest process diagram has been finalised ( #227) then add into the sphinx docs.

### PR DESCRIPTION
**Pull request by paigeh1**
Closes #254 . Other comments I made are in the issue #254 .

### CODE REVIEW

**Comment by jwestw** [comment]
The one thing I would suggest @paigeh1 is that the diagram in the README links through to the diagram file, so people can see a larger, zoomed in version if they wish

**Comment by nkshaw23** [comment]
Hyperlink at the bottom of `resources` section of the `The Public Transport Accessibility Project` page doesnt work.

**Review by jwestw — CHANGES_REQUESTED** [review]
Please change the image on the README so it links though to the original full scale image. 

Also, according to @nkshaw23 the URL link under resources doesnt work for him. Can that be fixed?

**Comment by paigeh1** [comment]
Changes that have been requested have now been resolved

**Review by jwestw — APPROVED** [review]
I had a look at the new build, looks good!

**Review by nkshaw23 — APPROVED** [review]

**Pull request merged**
