### PR TITLE
Cleaning up master

### PR DESCRIPTION
**Pull request by james-westwood**
I just wanted to tidy up the code, files and folders a bit.

Changes I have made:

- Linted the code in main
- Created a .pep config for other devs to use with autopep8
- deleted random data files
- created an data output folder
- re-routed the data output in to the output folder
- deleted notebook (isochrone experiments one)
- deleted junk module - databasemods.py
- updated the environment yaml  (this is the trickiest change) I suggest testing this by creating a new environment from it and seeing if the code runs.

### CODE REVIEW

**Comment by james-westwood** [comment]
Only need to look at these commits - they cover what I have described in the changes above

image

**Comment by nkshaw23** [comment]
Fixed merge conflicts from #329 and then linted the new code using flake8.

**Comment by nkshaw23** [comment]
Bug found when running pipeline after inserting `.gitkeep` files. Fixed in the above commit and whole pipeline tested.

Closes #341

**Comment by Antonio-John** [comment]
Having some struggles with the new virtual environment. I'll preserve for now and detail the blockers i'm getting but may need to ask for help.

**Comment by jwestw** [comment]
Okay. Let us know what the snags are and we can try to troubleshoot. It would be good to get a definitive dependencies list together as we approach version 1.0.

**Comment by nkshaw23** [comment]
Just tried creating a new environment using the `.environment.yml`: `conda env create --name SDG_yaml --file=environment.yml python=3.8` and ran into `ResolvePackageNotFound` errors.

This listed lots of packages under `dependencies` that couldn't be found. [This is because](https://stackoverflow.com/questions/55554431/conda-fails-to-create-environment-from-yml) the yaml contains platform specific build constraints e.g. `=hf or =py38`. I assume that the environment.yml was created in a linux environment?

I solved this by removing these (see attached environment_no_builds.yml) or you could add the `--no-builds` tag when creating the `.yml`.

[environment_no_builds.zip](https://github.com/ONSdigital/SDG_11.2.1/files/10011423/environment_no_builds.zip)

Creating the environment again got much further but left a few dependencies that still couldn't be resolved

Capture

[This looks to be because](https://stackoverflow.com/questions/50554467/resolve-package-not-found-error-in-anaconda) they only exist for linux / mac os so I cant install them on my windows machine. Searching for a couple in anaconda cloud showed no version for windows, and there was nothing on PyPi. Hence, im not sure how we would deal with these dependencies if we wanted a user to create the environment on any OS.

**Comment by jwestw** [comment]
If requirements txt works then let's use it!

I thought the conda envionment yaml was a bit more robust, but maybe the extra parameters in there make it more problematic when sharing over different OSs. 

Has anyone used [Poetry](https://python-poetry.org/)? Maybe this is a solution. Then again, if requirements.txt works, let's not do something else to 'fix' it.

**Comment by jwestw** [comment]
> [This looks to be because](https://stackoverflow.com/questions/50554467/resolve-package-not-found-error-in-anaconda) they only exist for linux / mac

Yes they definitely look like *nixy libraries.

**Comment by nkshaw23** [comment]
We updated the notes for developers in the docs when I joined the team and tested the process so should all work i.e. `requirements.txt` for packages

**Comment by jwestw** [comment]
We have decided to make a requirements txt by hand, by:
- looking at each .py file to see what third party imports are made, and make each a requirement
- looking at the version numbers of those libraries from the environment yaml which has already been committed

Also:
- Delete the environment yaml 

Paige will create a new environment and try to run the pipeline.

**Comment by nkshaw23** [comment]
`Requirements.txt` cleaned to just the required packages but having trouble setting up environment through conda as per instructions in the docs. The only way I can create the correct environment is `pip install requirements.txt`.

Suggesting we move this discussion to #203 (where I have left some comments on my issues) and then close this PR. The updated `environment.yml` has no effect on whether someone can setup an environment for the project because its currently not used.

**Review by nkshaw23 — APPROVED** [review]

**Pull request merged**
