### PR TITLE
263 produce sex pop estimates scotland

### LINKED ISSUE #263: Produce Whole SDG Pop Estimates for Scotland by sex
This is to produce estimates based on Male/Female split.
Steps for Developer:
- The data for Male/Female on an output area is contained with the Scottish Usual Population file already read in.
- Apply these disaggregation in a similar way to the way the SDG England & Wales script performs this.

### PR DESCRIPTION
**Pull request by paigeh1**
Closes #263 . 

Here is an example of what it outputted:

image

Any feedback is welcome!

### CODE REVIEW

**Comment by jwestw** [comment]
Hey @paigeh1 please can you look into making a data cleaning stage that standardizes column values to "Male" and "Female".

**Comment by Antonio-John** [comment]
We are using local authority boundaries of 2021. Does it make more sense to put the year as 2021 instead of 2011? The lookupfile goes from OA11CD TO LAD21NM and there will be other lookupfiles for other lad years. 

I suspect if we put the year as 2011, that is the only estimate that Scotland would get. 

Let me know if you have strong opinions on it either way :)

**Comment by paigeh1** [comment]
Taken on board James' comment and put it the same as `SDG_11.2.1_main.py`
image

Antonio to create an issue to look into sourcing 2011 local authority boundary data.

**Comment by Antonio-John** [comment]
Ticket created #285 to use 2011 La Boundaries for Scotland.

**Comment by Antonio-John** [comment]
Happy to merge in. #206 and #285 need to be completed next.

**Review by Antonio-John — COMMENTED** [review]
Great work! #285 & #206 just need doing now :)

**Review by Antonio-John — APPROVED** [review]

**Pull request merged**
