### PR TITLE
Handle zeros #153

### LINKED ISSUE #153: Handle zeros in `served_proportions_disagg`
When the population is zero (for example in the city of London there are zero rural population), the `served_proportions_disagg` function will error. 

This is probably also the case in SDG_11.2.1_main.py where `la_results_df` is being calculated.

### PR DESCRIPTION
**Pull request by james-westwood**
- This should handle zeros in dataframe as we discussed in a meeting about #153 
- Outputs string "None" for percentages instead of blanks as a requirement from SDG team

Merging back into the branch for #112 because that's where I branched from.

closes #153

### CODE REVIEW

**Comment by Antonio-John** [comment]
image

**Comment by Antonio-John** [comment]
- I think the number in cell L4 should be 100 instead of 1? Unless I am missing something. I.e 100% of the residents of the city of London have access to transport.

**Comment by james-westwood** [comment]
Hi @Antonio-John Thanks for the thorough check. 

image


I have fixed the problem with the most recent commit https://github.com/ONSdigital/SDG_11.2.1/pull/172/commits/1a081badccb3504fa65f737b03b538440346c3e6 You should see from the picture that the output is correctly formatted. 

It sounds plausible that 100% of people in the City of London are serviced by public transport so I don't think we need to check into the numbers.

**Comment by Antonio-John** [comment]
That's great @james-westwood output looks good and code runs successfully on my machine.

**Pull request merged**
