### PR TITLE
Create non disabled data 173

### LINKED ISSUE #173: Create "non-disabled" data for every local authority
Currently each LA has the data calculated for the number of people with disabilities, but not without disabilities. 

Previously this was understood (wrongly) to be included in all the other data, but these are totals for the other aggregates and disaggregations. 

Each LA needs the calculations for "non-disabled" while every other dimension is "Total" (blank).

### PR DESCRIPTION
**Pull request by jwestw**
Closes #173

### CODE REVIEW

**Comment by paigeh1** [comment]
We checked the figures for non-disabled and disabled in another LA and found that some percentages (those highlighted in yellow) only show 1 d.p. because the values to 2 d.p. include 0 (e.g. 93.10). This is probably due to the way that Excel reads values in the csv file. Do you think this is something worth reviewing?

b3507d22-8b1c-42c4-9cf4-2fefbe8d7a0b

**Comment by jwestw** [comment]
I will be reviewing my code here and updating if necessary today. Thanks for your reviews.

**Comment by jwestw** [comment]
> We checked that the figures for disabled/non disabled summed to the total population. We noticed that there is no total population row (served+unserved). We created the yellow row as an example. Is this required? @james-westwood
> 
> image

I am pretty sure this would be necessary, yes. I will look into why this is not being created. It will be another ticket if the code needs to be changed.

**Comment by jwestw** [comment]
> We checked the figures for non-disabled and disabled in another LA and found that some percentages (those highlighted in yellow) only show 1 d.p. because the values to 2 d.p. include 0 (e.g. 93.10). This is probably due to the way that Excel reads values in the csv file. Do you think this is something worth reviewing?
> 
> b3507d22-8b1c-42c4-9cf4-2fefbe8d7a0b

This is defintely worth reviewing. I think, as you have suggested, this might be an issue with Excel not displaying the zero when it is the last digit. I will look into this though.

**Comment by james-westwood** [comment]
@paigeh1 it seems to be showing up in only one d.p. in Pandas too. Just taking the last line of your screenshot for example.

image

**Review by Antonio-John — APPROVED** [review]

**Pull request merged**
