### PR TITLE
331 tidy up for bustrain timetable process

### LINKED ISSUE #331: Tidy up for bus/train timetable process
General tidy up for this part of the pipeline

- Check all docstrings are up-to-date on created functions
- Ensure all sphinx documentation is up-to-date and published
- Make sure notes about guidance + methodology are up-to-date (#289 #290)

### PR DESCRIPTION
**Pull request by jwestw**
## Pull Request submission 

- Renamed `SDG_11.2.1_main.py` into `main.py` - hopefully this is an identical change on other branches that I have made recently so won't create too much conflict
- Move all Python files into a folder called `src`
- Moved all timetable related processes into a folder called `time_table` under `src`
- Extracted all of the mca and msn data parsing into a `time_table_utils.py` file
- Any other functions which are timetable related, like `add_stop_capacity_type` have also been moved to the utils
- Linted and linted again, plus some manual changes

No new requirements are needed to run this.

No new data is required to run this. 

#### Closes or fixes

Fixes #331 

#### Code

- [x] **Requirements** My/our code matches the requirements of the ticket
- [x] **Functionality**: New functions meet requirements in issue ticket
- [x] **Compliant Code** Code is as [PEP 8]([url](https://peps.python.org/pep-0008/)) compliant as I can humanly make it
- [x] **Code runs** The code runs on my machine
- [x] **Clean Code** 
    - [x] Code has been linted (use your favourite linter)
    - [x] Code adheres to [DRY]([url](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)) 

#### Documentation

Any new code includes all the following forms of documentation:

- [x] **Function Documentation** Docstrings within the function(s') definition(s) have been created
    - [x] Includes `args` and `returns` for all major functions 
    - [x] Includes data types
- [ ] **Updated Documentation**: Working doc has been updated and a new ticket to update the master documentation has been created. 

#### Data
- [ ] All data needed to run this script has been added to Sync **N/A**

#### Testing
- [x] **Unit tests** Unit tests have been created and are passing _or a new ticket to create tests has been created_  https://github.com/ONSdigital/SDG_11.2.1/issues/372

---

# Peer Review Section

- [ ] All requirements install from (updated) `requirements.txt`
- [ ] Documentation has been created and is clear - check the google Doc
- [ ] Doctrings ([Google format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)) have been created and accurately describe the function's functionality
- [ ] Unit tests pass, or if not present _a new ticket to create tests has been created_
- [ ] **Code runs** The code runs on reviewer's machine

#### Final approval (post-review)

The author has responded to my review and made changes to my satisfaction.
- [ ] **I recommend merging this request.**

---

### Review comments

*Insert detailed comments here!*

These might include, but not exclusively:

- bugs that need fixing (does it work as expected? and does it work with other code
  that it is likely to interact with?)
- alternative methods (could it be written more efficiently or with more clarity?)
- documentation improvements (does the documentation reflect how the code actually works?)
- additional tests that should be implemented (do the tests effectively assure that it
  works correctly?)
- code style improvements (could the code be written more clearly?)

Your suggestions should be tailored to the code that you are reviewing.
Be critical and clear, but not mean. Ask questions and set actions.

### CODE REVIEW

**Comment by james-westwood** [comment]
I have killed off all conflicts by rebasing master into this branch - hopefully keeping all my changes. 

I have checked, and the code now works for me.

**Comment by james-westwood** [comment]
Just done a final linting with autopep8 to really tidy this up.

**Review by nkshaw23 — DISMISSED** [review]
Code tested for bus and train timetable data creation, main (for Hastings), scotland (for Fife) and NI (for Omagh).

NI cannot run due to sex disaggregation issue, but other LAs run with served populations matching our QA outputs.

**Comment by nkshaw23** [comment]
One issue to resolve.

When I run `SDG_bus_timetable.py` I need to add `src` to the `data_output` import in `data_transform`.

However when I run `main` I then need to remove it.

Is there a way we can have it imported that satisfy both modules

**Comment by jwestw** [comment]
I have sorted the problem RE: local imports of our own modules from the scr folder. The timetable python files are now all within scr, the parent is added to path, and this solves the problem. `src.` is not needed anywhere now. 

I have also re-linted.

And I have re-based so there are no conflicts with `master`

@nkshaw23 please review and approve.

**Review by nkshaw23 — APPROVED** [review]
bus timetable and main modules work for me.

**Pull request merged**
