### PR TITLE
fixing bug for ftp

### PR DESCRIPTION
**Pull request by Antonio-John**
I think the bug was to down to the formatting of paths with "//" and "/". Perhaps Mark was using an OS which had different paths? I've tried to use the os library where possible, so hopefully consistent going forward.

### CODE REVIEW

**Comment by Antonio-John** [comment]
If you could check the new code works :) I would just do a full run of up to ```ftps.execute_file_grab(CWD)``` to ensure you have everything downloaded. Then delete a few files and hopefully the code will know to download these missing files.

**Review by paigeh1 — APPROVED** [review]
I checked that when I deleted files it only downloaded the ones that were missing. I also checked that when I ran it with all files it says no files missing. Happy to approve this on my end. @jwestw will also need to review this on his computer as it may vary with different operating systems.

**Comment by jwestw** [comment]
This is not working on a Linux system.

**Comment by jwestw** [comment]
As the ftp bug could not be fixed easily, we have decided to get rid of the ftp functionality all together.

**Review by jwestw — APPROVED** [review]
We have decided to get rid of the call to the ftp module as we are still finding it buggy. We will eventually completely replace this with another online storage solution.

**Pull request merged**
