### PR TITLE
Extracting out pre processing for england and wales.

### LINKED ISSUE #380: Extract pre-processing for england and wales and reafctor main.py
- Refactor current code to extract all the processing into its own script for england and wales.
- Restructure processing into blocks of code for each layer (data source).
- Save datasets to feather to be imported into main
- Tidy and refactor main

### PR DESCRIPTION
**Pull request by nkshaw23**
## Pull Request submission 

Several large changes

- All preprocessing steps have been taken out of the pipeline and collected in one place.
- Preprocessing outputs saved as feather (non-spatial) / geojson (spatial) files for the main pipeline
- Main pipelines updated from (1) and (2) accordingly, restructures for improved readability and cleaned.
- Code added to allow pipeline to be run for various countries
- Variable names and scripts and config made consistent
- Removed `naptan_df` import into train timetable script. This was imported from `main`, but we need to run train timetable before `main`. Now loads directly into the train timetable script.
- Removed `create_tiploc` in preprocessing as it is only run for trains, but then we subset for trams so doesnt get used. Moved to train timetable as only applicable for trains.
- `Station locations.csv` no longer needed so removed from code and from sync.
- Further tidy (removing duplicate functions + linting)

Tested full pipeline (bus feather files, train feather file, whole nation pop file and stops feather all deleted) and compared to outputs in #352 . Advise testers to do the same (the whole nation pop takes a while so you can keep this if you want). 

Run timetable scripts, then eng_wales processing module and then `main.py` to test england_wales

#### Closes or fixes

Closes #380 

#### Code

- [x] **Requirements** My/our code matches the requirements of the ticket
- [x] **Functionality**: New functions meet requirements in issue ticket
- [x] **Compliant Code** Code is as [PEP 8]([url](https://peps.python.org/pep-0008/)) compliant as I can humanly make it
- [x] **Code runs** The code runs on my machine
- [x] **Clean Code** 

---

### CODE REVIEW

**Comment by jwestw** [comment]
@nkshaw23 Good work! I will try to pull this and run today

**Comment by jwestw** [comment]
# Peer Review Section

- [ ] All requirements install from (updated) `requirements.txt`
- [ ] Documentation has been created and is clear - check the google Doc
- [ ] Doctrings ([Google format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)) have been created and accurately describe the function's functionality
- [ ] Unit tests pass, or if not present _a new ticket to create tests has been created_
- [ ] **Code runs** The code runs on reviewer's machine

#### Final approval (post-review)

The author has responded to my review and made changes to my satisfaction.
- [ ] **I recommend merging this request.**

---

### Review comments

*Insert detailed comments here!*

These might include, but not exclusively:

- bugs that need fixing (does it work as expected? and does it work with other code
  that it is likely to interact with?)
- alternative methods (could it be written more efficiently or with more clarity?)
- documentation improvements (does the documentation reflect how the code actually works?)
- additional tests that should be implemented (do the tests effectively assure that it
  works correctly?)
- code style improvements (could the code be written more clearly?)

Your suggestions should be tailored to the code that you are reviewing.
Be critical and clear, but not mean. Ask questions and set actions.

**Comment by jwestw** [comment]
I tried to follow the instructions, i.e. running the timetable scripts, then running `main.py`, but I am getting an error on line 69 of `src/SDG_eng_wales.py`

```console
File "/home/james/programming/work-related/SDG_11.2.1/src/SDG_eng_wales.py", line 69, in <module>
    list_local_auth = ew_la_df[lad_col].unique()
NameError: name 'ew_la_df' is not defined
```

This is because 'ew_la_df' is define on line 51, but is behind an `if` clause which is not testing as true in my instance. Since the `ew_la_df_path` does not exist, so the df is not defined.

**Review by jwestw — COMMENTED** [review]
I tried to follow the instructions, i.e. running the timetable scripts, then running `main.py`, but I am getting an error on line 69 of `src/SDG_eng_wales.py`

```console
File "/home/james/programming/work-related/SDG_11.2.1/src/SDG_eng_wales.py", line 69, in <module>
    list_local_auth = ew_la_df[lad_col].unique()
NameError: name 'ew_la_df' is not defined
```

This is because 'ew_la_df' is define on line 51, but is behind an `if` clause which is not testing as true in my instance. Since the `ew_la_df_path` does not exist, so the df is not defined.

**Comment by paigeh1** [comment]
I've also ran this - there are a couple issues with the pipeline so far. We have managed to resolve some of them - @nkshaw23 is having a look at an issue where we need to resolve importing modules to other modules due to different directories. Currently, there is an issue with importing `data_ingest` in `data_transform` when we run the `eng_wales_pre_process.py` because of different directories.

I've managed to make temp fixes to test the rest of the pipeline and it runs for me. However, I've found something interesting with the local authority 'Hastings'. There doesn't seem to be any information for rural population in Hastings. Maybe Hastings is completely rural and this is fine.

It also seems a bit strange that both the proportion of males and females are being served by public transport with the exact same percent. I ran for another local authority and the same issue occurs too. 

This screenshot shows the output for local authority Hastings (with Urban/Rural and sex issue)
Screenshot 2023-03-03 at 16 02 05

This screenshot shows the output for local authority Somerset West and Taunton with the sex issue

Screenshot 2023-03-03 at 16 05 48

**Comment by nkshaw23** [comment]
**RE Sex**

There is something weird going on in your screenshots. The total population for `Hastings` is almost 7 million! and actually, because you have such a large value here, the percentages for the sex are actually correct when rounded to 2 dp.

When i run it I get these overall population figures in the console, and then we can see this in the CSV and that the sex calculation looks to be correct, and the totals for each sex match the totals for overall population and served/unserved.

image

image

Same thing going on for Somerset and West Taunton - almost 8,000,000 people!

**Comment by nkshaw23** [comment]
**RE time taken**

Mine seems to be taking roughly the correct amount of time (at least compared to the current way of running) - about 2 minutes. If you had the debugger on and working through the code, then be aware the time calculated at the end will take this into account. Other than that, might have just been a slow day?

image

**Comment by nkshaw23** [comment]
Changes from @paigeh1 testing, and changes discussed above have been pushed. 

Latest instructions for testing @Antonio-John @james-westwood 

1) Delete everything in `england_bus_timetable` directory (except `.gitkeep`)
2) `england_train_timetable` directory should look like this

image)

3) Delete `RUC11_OA11_EW.feather` from `data` directory
4) Delete `whole_nation_2019.feather` from `data` directory (optional, as this takes a while to rebuild)
5) Make sure you have a `eng_wales_preprocessed` directory.
6) Run `SDG_bus_timetable`
7) Run `SDG_train_timetable`
8) Run `eng_wales_pre_process`
9) Run `main`

Note that scotland and NI will now not run because we have changed `main`. There are tickets out to update scotland and NI to match the template of England/Wales which I can do after this has been tested and merged.

**Comment by jwestw** [comment]
I get an error when following these instructions. Just to make sure this wasn't due to my local machine being weird, I tried it on a Google VM too and I get the same error. 

I have uploaded the entire output of the stack trace here:
[stacktrace.txt](https://github.com/ONSdigital/SDG_11.2.1/files/11000629/stacktrace.txt)

`pandas.errors.EmptyDataError: No columns to parse from file` is occuring when `di._csv_to_df(...` is being called on line 122 of `SDG_bus_timetable.py` 

So why is this happening? I am pretty sure I have seen this same error some months back. 

After I deleted the data from `data/england_bus_timetable` it all had to be replaced. The process of downloading and extracting that seems to go smoothly, but actually `trips.txt` and `calendar.txt` are empty. (`stop_times.txt` is not however). 

Then when `di._csv_to_df()` calls `pd.read_csv()` it fails. 


I think this is an issue with the downloading and extracting of the bus data, rather than the code you've refactored here - and this is why I think I saw this months ago.

**Comment by jwestw** [comment]
It's worth noting that when I run this in a fresh environment with no data in it, when I run `eng_wales_pre_process.py`

I get:

```console
FileNotFoundError: [Errno 2] No such file or directory: 'data/england_bus_timetable/bus_highly_serviced_stops.feather'
```

**Comment by jwestw** [comment]
Going back to  to debug. In debug mode I get no errors. It seems to just run and complete. 

However, in normal Python I get "killed" at the end of the process. 

image


You might remember that from here: https://github.com/ONSdigital/SDG_11.2.1/pull/350#pullrequestreview-1220949363

**Comment by jwestw** [comment]
I have upped the RAM on the GCP VM to 16GB. 

The memory used by the script is over 8GB

image

This time `bus_highly_serviced_stops.feather` was successfully written out.

**Comment by jwestw** [comment]
# Peer Review Section

- [x] All requirements install from (updated) `environment.yml`  <- I didn't use the requirement.txt
- [ ] Documentation has been created and is clear - check the google Doc
- [x] Doctrings ([Google format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)) have been created and accurately describe the function's functionality
- [x] Unit tests pass, or if not present _a new ticket to create tests has been created_
- [x] **Code runs** The code runs on reviewer's machine

#### Final approval (post-review)

The author has responded to my review and made changes to my satisfaction.
- [x] **I recommend merging this request.**

---

### Review comments

I have checked through all the code and it looks good. I have created a new ticket #408 because rebuilding the whole-nation pop file took ridiculously long.

- We should either
    - Optimise the scripts so they use less memory
    - Put some minimum system requirements on running the script. Running out of memory was quite confusing because "killed" isn't very explicit


I don't think I can see anything in the WIP docs about these changes. I think we would need to instruct users on how to run this - i.e. what order to run the scripts.

**Review by jwestw — APPROVED** [review]
Approved as per last comment.

**Pull request merged**
