### PR TITLE
303 age disaggregation for scotland

### PR DESCRIPTION
**Pull request by Antonio-John**
This is for age disaggregation for Scotland. To run this code the QS103_scotland_age.csv will need to be downloaded from the Sync Website.

### CODE REVIEW

**Review by paigeh1 — COMMENTED** [review]
Great work on this!! Everything checks out, but I have a couple things that I probably suggest changing before we merge this. When looking at the data, I noticed for age being 0-4, it says under 1 - 4, can this be changed to 0-4? Similar with 100+, it says 100 and over-100 and over (presume from adding them all together), can this be 100+ please? :)

**Comment by Antonio-John** [comment]
Have changed the column names to 0-4 & 100+ :)

**Comment by james-westwood** [comment]
I don't have very strong opinions on this.

For comparison reasons we need to make the outputs the same, so we need to change one or the other. Since we can't create granularity where there is none, so we probably need to go with the limitations of the most limited (least granular) dataset, so that means forcing the Scotland data into the same categories as the E+W data. 

Happy to ask the advice of the SDG team if needed.

**Comment by Antonio-John** [comment]
thanks for the advice @james-westwood I'll make them consistent and mention this in the google doc.

**Comment by Antonio-John** [comment]
Merge this for now and address the 90+ age inconsistency with the ticket #340

**Review by paigeh1 — APPROVED** [review]
Happy to approve, great work! Only thing is it says 100 on the output. When you get to the consistency ticket, can you get this changed to 90+ please? Also, please add some stuff to the documentation if that hasn't already been done :)

**Comment by jwestw** [comment]
@paigeh1 I know this is Antonio's PR, but it's getting a bit old now, so the sooner we merge it the better. There are some conflicts we will need to resolve before going ahead though. I have had a look and they are not massive so we can get them resolved quickly.

**Comment by paigeh1** [comment]
Fixed merge conflicts

**Pull request merged**
